export let newNews = [
  // Emergency news1
  {
    lastActivated: "",
    active: false,
    expires: false,
    title: "Template! This is a template!",
    lines: ["today and yesterday, if you didn't know", "this is a template"],
    md: "",
    link: "",
  },
  // Emergency news 2
  {
    lastActivated: "",
    active: false,
    expires: false,
    title: "Template! This is a template!",
    lines: ["today and yesterday, if you didn't know", "this is a template"],
    md: "",
    link: "",
  },
    {
    lastActivated: "260108",
    active: true,
    expires: 260210,
    title: "Upcoming Backfip-A-Thon Fundraiser",
    lines: ["Saturday 1.31, 7pm!", "Details below!"],
    md: "",
    link: "./events/260131/backflip-a-thon.html",
  },
    // 5th thursday cancellation
  {
    lastActivated: "250720",
    active: true,
    expires: 250801,    
    title: "[7/31/Thurs] 5th Thurs, No Classes! 🙅",
    lines: [
      "Axis is closed on the 5th Thursday since we only have 4 classes in each session!",
      // "It also happens to be Halloween so have fun and stay safe!",
      "enjoy the day off! :-)"
    ],
    md: "",
    link: "",
  },
  // discord announcement 2024
  {
    lastActivated: "9.15.24",
    active: true,
    expires: false,
    title: "Seattle Tricking Discord",
    lines: [
      "Get notified of updates, announcements, and more!",
      "click here for the full details!",
    ],
    md: "./discord/discord.md",
    link: "./discord.html",
  }, // december workshops
  //
];
// ===========================================================
// ==================Archived==================Archived=======
// ===========================================================
let archived = [
    {
    lastActivated: "251008",
    active: false,
    expires: 260130,
    title: "Thursday Schedule through Jan! ",
    lines: ["Holiday Closures, Workshops, etc!"],
    md: "./events/2511-holiday-class-schedule/schedule.md",
    link: "",
  },
    {
    lastActivated: "2510024",
    active: true,
    expires: 251203,
    title: "Friday sesh starting at 7:30pm",
    lines: ["From 10/31 til next summer :)","Mondays remain 7-9pm!"],
    md: "",
    link: "",
  },
        {
    lastActivated: "251107",
    active: true,
    expires: 251117,
    title: "Free Injury Screening Night(s)!",
    lines: [
      "Free with Open Session drop-in OR membership tally ",
      "Sunday 11.16",
    ],
    md: "./events/empower/injury-screening.md",
    link: "",
  },
    {
    lastActivated: "251008",
    active: true,
    expires: 251101,
    title: "Halloween Tricks n' Treats Sesh!",
    lines: ["Friday 10/31!, costume sesh, games, and potluck!", ""],
    md: "./events/251031-halloween/event.md",
    link: "",
  },
      {
    lastActivated: "250826",
    active: true,
    expires: 250902,    
    title: "labor Day week schedule!",
    lines: [
      "Thursday & Friday normal",
      "Saturday Not a Gathering (3)",
      "Sunday normal",
      "Monday no gym sesh, maybe outside!"
    ],
    md: "./events/2025LaborDayMini/weekend-schedule.md",
    link: "",
  },
  {
    lastActivated: "250720",
    active: true,
    expires: 250902,
    title: "Not A Gathering 3: Labor Day Mini",
    lines: [
      "click for details and registration!",
      "Saturday: August 30",
    ],
    md: "",
    link: "./events/2025LaborDayMini/not-a-gathering.html",
  },
    {
    lastActivated: "250720",
    active: true,
    expires: 250814,
    title: "Northbound i5 lane reductions!",
    lines: ["there may be heavier traffic than normal.",  "People have been reporting 15-20m extra if coming from south!"
    ],
    md: "",
    link: "https://x.com/wsdot_traffic",
  },
    {
    lastActivated: "250720",
    active: true,
    expires: 250726,
    title: "Free Injury Screening Night!",
    lines: [
      "Free with Open Session drop-in OR membership tally ",
      "Friday 7/25 starting at 7:30pm!",
    ],
    md: "./events/archived/2024empower/injury-screening.md",
    link: "",
  },
    {
    lastActivated: "2.17.25",
    active: false,
    expires: false,
    title: "Free Injury Screening Night(s)!",
    lines: [
      "Free with Open Session drop-in OR membership tally ",
      "Sunday 12.8, Friday 12.13",
    ],
    md: "./events/2024empower/injury-screening.md",
    link: "",
  },
    {
    lastActivated: "250630",
    active: true,
    expires: 250705,
    title: "4th of July Sesh!",
    lines: ["4pm at Medina park near bellevue!", "check meetups tab in the discord!"],
    md: "",
    link: "",
  },
  {
    lastActivated: "",
    active: true,
    expires: 250630,
    title: "PDX Field Trip! RCG4: June 27-29",
    lines: ["Rose City Gathering in Vancouver, WA","Carpool survey out now!! please fill out ASAP :-)"],
    md: "./events/2025rcg4/rcg4.md",
    link: "",
  },
    {
    lastActivated: "",
    active: true,
    expires: 250607,
    title: "Friday Hours Changing!",
    lines: ["Open Tricking: 8-10pm starting 5.2"],
    md: "./events/summer-friday-hours.md",
    link: "",
  },
    {
    lastActivated: "",
    active: false,
    title: "[11am/6.1/Sun Karate Kid viewing]",
    lines: ["Aj is literally the karate kid!",
      "We're obv having a watch party! details below!",
    ],
    md: "./events/250601karatekid.md",
    link: "",
  },
  {
    lastActivated: "3.12.25",
    active: false,
    title: "[Saturday/4.12] Portland Earth Day Invitational",
    lines: ["Portland's annual tricking event is back!","More details below!"],
    md: "./events/2025earthday.md",
    link: "",
  },
  {
    lastActivated: "2.17.25",
    active: false,
    title: "[Sunday/3.9/5:15pm] Neck Clinic for Dynamic Athletes!",
    lines: ["Dr. Gina from Empower is back with special tests and accompanying exercises to keep ya neck in check","Free with session drop-in fee or membership tally"],
    md: "",
    link: "",
  },
  {
    lastActivated: "2.6.25",
    active: false,
    title: "2.6 Thursday Classes Cancelled due to Snow and Icy roads",
    lines: ["Hello! There's still a lot of snow and slush on the road.  It may melt later today, whatever melts today is projected to freeze over tonight.",
           "Tricking Foundations and Flipping progressions will be canceled for tonight!", "We will do a 3 week cycle starting next week :)"],
    md: "",
    link: "",
  },
    {
    lastActivated: "2.2.25",
    active: false,
    title: "Snow Expected This Week! 2.2 - 2.9 ❄️",
    lines: ["1. If you don't have experience driving in the snow in hilly seattle, do not learn in real time.", "2. Check the weather in your area BEFORE you leave for any sesh this week", "3. Go play in the snow when available!!!!!"],
    md: "",
    link: "",
  },
  {
    lastActivated: "1/6/25",
    active: true,
    title: "J&K on Holiday 🌴🏖️🌊",
    lines: ["1/19-1/29", "Classes May Be Affected!"],
    md: "./events/jkholiday.md",
    link: "",
  },
  {
    lastActivated: "12/30/24",
    active: true,
    title: "New Years Week",
    lines: [
      "12/31 Tuesday Guided Tricking and Exercise as Normal!",
      "NYE Games, Potluck, and Sesh Following Tuesday Exercise (9:30ish)",
      "Thursday 1/2 starts the next Cycle of Tricking Foundations!",
    ],
    md: "",
    link: "",
  },
  {
    lastActivated: "12/23/24",
    active: true,
    title: "Christmas Week Closures 🎅🤶🎄🦌🛷",
    lines: [
      "Monday Sesh Tentative! Check the Mon/Friday Discord to vote yes if you're in town!",
      "Tuesday-Thursday: Axis is Closed for Christmas!",
      "Friday Open sesh as normal",
    ],
    md: "",
    link: "",
  },
  {
    lastActivated: "11.6.24",
    active: false,
    title: "December Thursday Workshops",
    lines: [
      "6:30-7:30pm replacing December Foundations class!",
      "Workshops Schedule 👇",
    ],
    md: "./events/workshops/december-workshops.md",
    link: "",
  },
  {
    lastActivated: "11.24.24",
    active: false,
    title: "Thanksgiving Day Closure! 🦃",
    lines: [
      "No Classes on Thursday this week!",
      "Regular Thursday classes will be on Wednesday at the same time instead!",
    ],
    md: "",
    link: "",
  },
  {
    lastActivated: "11.15.24",
    active: true,
    title: "⚠️Construction⚠️ Parking may be affected",
    lines: [
      "Mon-Thurs, 11.18-21",
      "Landlord is fixing concrete, weather permitting",
      "Might want to get there a little early and with rain gear in case of tough parking",
    ],
    md: "",
    link: "",
  },
  // Emergency news 2
  {
    lastActivated: "",
    active: false,
    title: "Bomb Cyclone Advisory! Be Prepared! 🌪️",
    lines: [
      "Prepare for power outages, high winds, and snow*",
      "Update as of 2:30pm: Tuesday classes are on!",
    ],
    md: "./events/24bombcyclone.md",
    link: "",
  },
  {
    lastActivated: "10.28.24",
    active: false,
    title: "PDX Tricksgiving Fieldtrip",
    lines: ["Sat, Nov 16 @ 6:30pm", "Carpool survey due by Tuesday ⚠️"],
    md: "./events/2024pdxtricksgiving/2024pdxtricksgiving.md",
    link: "",
  },
  {
    lastActivated: "11.10.24",
    active: false,
    title: "Veteran's day Monday",
    lines: ["Axis 45 sesh will be as normal this monday :-)"],
    md: "",
    link: "",
  },
  // Halloween Sesh 2024
  {
    lastActivated: "10.21.24",
    active: false,
    title: "[11.1/Fri] Halloween Sesh!",
    lines: [
      "Costumes, Squid Games, and Food!",
      "Halloween falls on a Thursday this year, but that won't stop us from having",
      "a fun FRIDAY Halloween sesh 🎃",
    ],
    md: "./events/2024halloween/haloween.md",
    link: "",
  },
];
